CREATE TABLE IF NOT EXISTS users (
    clerkId TEXT PRIMARY KEY,
    firstName VARCHAR(255) NOT NULL,
    lastName VARCHAR(255) NOT NULL,
    bio VARCHAR(1000) NULL
);

CREATE TABLE IF NOT EXISTS posts2 (
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    clerkId_id TEXT REFERENCES users (clerkId),
    post VARCHAR(1000) NOT NULL
);

CREATE TABLE IF NOT EXISTS comments (
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    clerkId_id TEXT REFERENCES users (clerkId),
    post_id INTEGER REFERENCES posts2(id),
    comment VARCHAR(1000) NOT NULL
);